# Generated by Django 5.2.3 on 2026-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='average_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
