# Generated by Django 5.2.3 on 2026-05-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
        ('vision', '0002_uploadedvideo_average_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_videos', to='traffic.location'),
        ),
    ]
