# Generated by Django 5.2.3 on 2026-04-16 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('segment_id', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(default='Enugu', max_length=100)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('speed_limit', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('distance_km', models.FloatField()),
                ('est_time_min', models.IntegerField()),
                ('via_roads', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_routes_from', to='traffic.location')),
            ],
            options={
                'ordering': ['est_time_min'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('incident', 'Incident Report'), ('custom', 'Custom Report')], default='daily', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('summary_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='traffic.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('car_count', models.IntegerField(default=0)),
                ('truck_count', models.IntegerField(default=0)),
                ('motorcycle_count', models.IntegerField(default=0)),
                ('bus_count', models.IntegerField(default=0)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('free_flow_speed', models.FloatField(default=60.0)),
                ('queue_length', models.FloatField(default=0.0)),
                ('congestion_index', models.FloatField(default=0.0)),
                ('congestion_level', models.CharField(choices=[('free_flow', 'Free Flow'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('gridlock', 'Gridlock')], default='free_flow', max_length=20)),
                ('rainfall_mm', models.FloatField(default=0.0)),
                ('visibility_km', models.FloatField(default=10.0)),
                ('temperature_c', models.FloatField(default=28.0)),
                ('source', models.CharField(default='mock', max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='traffic.location')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='traffic_tra_locatio_de3400_idx'), models.Index(fields=['congestion_level', '-timestamp'], name='traffic_tra_congest_6c1430_idx')],
            },
        ),
    ]
