# Generated by Django 5.2.3 on 2026-04-16 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_url', models.CharField(blank=True, help_text='RTSP stream URL or path to local video file', max_length=500)),
                ('resolution', models.CharField(choices=[('480p', '480p SD'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4k', '4K Ultra HD')], default='1080p', max_length=10)),
                ('fps', models.IntegerField(default=30, help_text='Frames per second')),
                ('direction', models.CharField(blank=True, help_text='e.g. Northbound, Southbound', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='traffic.location')),
            ],
            options={
                'verbose_name': 'Camera',
            },
        ),
        migrations.CreateModel(
            name='IoTSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_type', models.CharField(choices=[('speed', 'Speed Sensor'), ('volume', 'Volume Counter'), ('occupancy', 'Occupancy Sensor'), ('weather', 'Weather Station')], default='volume', max_length=20)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('firmware_ver', models.CharField(default='1.0.0', max_length=50)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='traffic.location')),
            ],
            options={
                'verbose_name': 'IoT Sensor',
            },
        ),
        migrations.CreateModel(
            name='DeviceController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managed_cameras', models.ManyToManyField(blank=True, related_name='controllers', to='devices.camera')),
                ('managed_sensors', models.ManyToManyField(blank=True, related_name='controllers', to='devices.iotsensor')),
            ],
            options={
                'verbose_name': 'Device Controller',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.iotsensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
