"""
Core traffic domain models.
Location, TrafficReading, Report — the data layer used by all services.
"""
from django.db import models
from django.utils import timezone
from django.conf import settings


# ── Congestion levels ─────────────────────────────────────────────
class CongestionLevel(models.TextChoices):
    FREE_FLOW = 'free_flow', 'Free Flow'
    MODERATE  = 'moderate',  'Moderate'
    HEAVY     = 'heavy',     'Heavy'
    GRIDLOCK  = 'gridlock',  'Gridlock'

LEVEL_COLOR = {
    'free_flow': '#22c55e',
    'moderate':  '#f59e0b',
    'heavy':     '#f97316',
    'gridlock':  '#ef4444',
}


# ── Location ──────────────────────────────────────────────────────
class Location(models.Model):
    """A monitored road segment or intersection."""
    name        = models.CharField(max_length=200)
    segment_id  = models.CharField(max_length=100, unique=True)
    latitude    = models.FloatField()
    longitude   = models.FloatField()
    city        = models.CharField(max_length=100, default='Enugu')
    road_name   = models.CharField(max_length=200, blank=True)
    speed_limit = models.IntegerField(default=50)   # km/h
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"{self.name} ({self.city})"

    @property
    def latest_reading(self):
        return self.readings.order_by('-timestamp').first()

    @property
    def congestion_color(self):
        lr = self.latest_reading
        if lr:
            return LEVEL_COLOR.get(lr.congestion_level, '#6b7280')
        return '#6b7280'


# ── TrafficReading ────────────────────────────────────────────────
class TrafficReading(models.Model):
    """Time-series traffic reading from any source (IoT, mock, API)."""
    timestamp        = models.DateTimeField(default=timezone.now, db_index=True)
    location         = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name='readings'
    )

    # Vehicle counts
    vehicle_count     = models.IntegerField(default=0)
    car_count         = models.IntegerField(default=0)
    truck_count       = models.IntegerField(default=0)
    motorcycle_count  = models.IntegerField(default=0)
    bus_count         = models.IntegerField(default=0)

    # Speed & flow
    avg_speed         = models.FloatField(default=0.0)       # km/h
    free_flow_speed   = models.FloatField(default=60.0)      # km/h
    queue_length      = models.FloatField(default=0.0)       # metres

    # Derived congestion metrics
    congestion_index  = models.FloatField(default=0.0)       # 0–100
    congestion_level  = models.CharField(
        max_length=20,
        choices=CongestionLevel.choices,
        default=CongestionLevel.FREE_FLOW,
    )

    # Environmental
    rainfall_mm       = models.FloatField(default=0.0)
    visibility_km     = models.FloatField(default=10.0)
    temperature_c     = models.FloatField(default=28.0)

    # Source tracking
    source            = models.CharField(max_length=50, default='mock')

    class Meta:
        ordering = ['-timestamp']
        indexes  = [
            models.Index(fields=['location', '-timestamp']),
            models.Index(fields=['congestion_level', '-timestamp']),
        ]

    def __str__(self):
        return (
            f"{self.location.name} @ {self.timestamp:%Y-%m-%d %H:%M}"
            f" — {self.congestion_index:.1f}"
        )

    @property
    def level_color(self):
        return LEVEL_COLOR.get(self.congestion_level, '#6b7280')

    @property
    def level_badge(self):
        badges = {
            'free_flow': 'badge-success',
            'moderate':  'badge-warning',
            'heavy':     'badge-orange',
            'gridlock':  'badge-danger',
        }
        return badges.get(self.congestion_level, 'badge-secondary')

    @staticmethod
    def index_to_level(index: float) -> str:
        if index <= 25:  return CongestionLevel.FREE_FLOW
        if index <= 50:  return CongestionLevel.MODERATE
        if index <= 75:  return CongestionLevel.HEAVY
        return CongestionLevel.GRIDLOCK


# ── Report ────────────────────────────────────────────────────────
class Report(models.Model):
    """Generated by TrafficOfficer via DatabaseManager.save_report()."""
    REPORT_TYPE = [
        ('daily',   'Daily Summary'),
        ('weekly',  'Weekly Summary'),
        ('incident','Incident Report'),
        ('custom',  'Custom Report'),
    ]

    title         = models.CharField(max_length=300)
    report_type   = models.CharField(max_length=20, choices=REPORT_TYPE, default='daily')
    location      = models.ForeignKey(Location, on_delete=models.SET_NULL,
                      null=True, blank=True, related_name='reports')
    generated_by  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                      null=True, related_name='reports')
    period_start  = models.DateTimeField()
    period_end    = models.DateTimeField()
    summary_json  = models.JSONField(default=dict)
    created_at    = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} ({self.report_type})"


# ── AlternativeRoute ──────────────────────────────────────────────
class AlternativeRoute(models.Model):
    """Calculated by TrafficProcessor.calculate_alternative_routes()."""
    origin      = models.ForeignKey(Location, on_delete=models.CASCADE,
                    related_name='alternative_routes_from')
    description = models.TextField()
    distance_km = models.FloatField()
    est_time_min= models.IntegerField()
    via_roads   = models.CharField(max_length=500, blank=True)
    is_active   = models.BooleanField(default=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['est_time_min']

    def __str__(self):
        return f"Route from {self.origin.name}: {self.description[:60]}"
