"""
Alert model + NotificationService implementing UML:
  NotificationService: + sendAlert() + updatePredictiveData()
"""
from django.db import models
from django.utils import timezone
from apps.traffic.models import Location, CongestionLevel


class Alert(models.Model):
    """Traffic alert generated by NotificationService.send_alert()."""
    SEVERITY_CHOICES = [
        ('info',     'Info'),
        ('warning',  'Warning'),
        ('critical', 'Critical'),
    ]

    timestamp        = models.DateTimeField(default=timezone.now, db_index=True)
    location         = models.ForeignKey(Location, on_delete=models.CASCADE,
                         related_name='alerts')
    level            = models.CharField(max_length=20, choices=CongestionLevel.choices)
    severity         = models.CharField(max_length=10, choices=SEVERITY_CHOICES,
                         default='warning')
    message          = models.TextField()
    congestion_index = models.FloatField()
    is_resolved      = models.BooleanField(default=False)
    resolved_at      = models.DateTimeField(null=True, blank=True)
    resolved_by      = models.ForeignKey(
        'accounts.User', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='resolved_alerts'
    )

    class Meta:
        ordering = ['-timestamp']
        indexes  = [
            models.Index(fields=['-timestamp']),
            models.Index(fields=['is_resolved', '-timestamp']),
        ]

    def __str__(self):
        return f"[{self.severity.upper()}] {self.location.name} @ {self.timestamp:%H:%M}"

    def resolve(self, user=None):
        self.is_resolved = True
        self.resolved_at = timezone.now()
        self.resolved_by = user
        self.save(update_fields=['is_resolved', 'resolved_at', 'resolved_by'])

    @property
    def level_color(self):
        return {
            'free_flow': '#22c55e',
            'moderate':  '#f59e0b',
            'heavy':     '#f97316',
            'gridlock':  '#ef4444',
        }.get(self.level, '#6b7280')

    @property
    def severity_class(self):
        return {
            'info':     'alert-info',
            'warning':  'alert-warning',
            'critical': 'alert-danger',
        }.get(self.severity, 'alert-secondary')
